"""
Django settings for DoxPortal project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from datetime import timedelta

from django.utils.translation import gettext_lazy as _
from pathlib import Path

import sys
import os

from rest_framework.settings import api_settings


def get_site_packages():
    """ Возвращает полный путь к директории "site-packages" текущего окружения питон """
    # Пройдемся по всем системным путям,
    for path in sys.path:
        # и найдем путь оканчивающийся на'site-packages'.
        if path.endswith('site-packages'):
            # Этот путь и вернем.
            return path


# Build paths "site-packages" in python enviroment
SITE_PACKAGES_DIR = get_site_packages()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(f7z8oji6k_(_v6n8hl7pjop(blk7)(@9)0b92l$jn&9&(1&rn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEST_CAPTCHA = False

ALLOWED_HOSTS = []
INTERNAL_IPS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'main',
    'my_admin',
    'accounts',
    'common',
    'test_polygon',
    'rest_framework',
    'knox',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DoxPortal.urls'

TEMPLATES = [
    {
        'NAME': 'django',
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maintenance_mode.context_processors.maintenance_mode'
            ],
        },
    },
    {
        'NAME': 'jinja2',
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(SITE_PACKAGES_DIR, fr'django/forms/jinja2')],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'DoxPortal.jinja2.environment',
            'autoescape': False,
            'trim_blocks': True,
            'lstrip_blocks': True,
            "extensions": [
                "jinja2.ext.do",
                # "jinja2.ext.loopcontrols",
                # "jinja2.ext.with_",
                "jinja2.ext.i18n",
                # "jinja2.ext.autoescape",
                # "common.template_ext.globals.TemplateCacheExtension"
            ],
        }
    },
]

WSGI_APPLICATION = 'DoxPortal.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'EXCEPTION_HANDLER': 'common.helpers.small.dox_utils.custom_exception_handler',
    # 'NON_FIELD_ERRORS_KEY': "_",
}

REST_KNOX = {
  'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA512',
  'AUTH_TOKEN_CHARACTER_LENGTH': 64,
  'TOKEN_TTL': timedelta(hours=10),
  'USER_SERIALIZER': 'knox.serializers.UserSerializer',
  'TOKEN_LIMIT_PER_USER': None,
  'AUTO_REFRESH': True,
  'EXPIRY_DATETIME_FORMAT': api_settings.DATETIME_FORMAT,
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dox-portal-r',
        'USER': 'aborigen',
        'PASSWORD': 'shuXRz4hFeeAEsCU'
    }
}

REDIS = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'INDEX_DB': 1
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    },
    "redisCache": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        # "KEY_PREFIX": "cache"
    }
}

# Настройки электронной почты
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = '465'
EMAIL_HOST_USER = 'paradox81ru@yandex.ru'
EMAIL_HOST_PASSWORD = 'jgxvaczffgttdaba'
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = '587'
# EMAIL_HOST_USER = 'paradox81ru@gmail.com'
# EMAIL_HOST_PASSWORD = 'cosmOS_987'


SERVER_EMAIL = 'paradox81ru@mail.ru'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

LANGUAGES = (
    ('ru', _('Russian')),
    ('en', _('English')),
)

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = False

# Время в минутах до сброса количества неудачных заходов.
WAIT_RESET_FAILED_VALIDATE = 30

try:
    from DoxPortal.local_settings import *
except ImportError:
    pass
