# Generated by Django 4.1.7 on 2023-03-28 11:49

from django.db import migrations, models


def load_fixtures(apps, schema_editor):
    # This is what will be executed by the migration
    from django.core.management import call_command
    # this is the equivalent of running manage.py loaddata yourmodel.json
    call_command("loaddata", 'initial_paradox_data.yaml')
    # add other calls if you have multiple models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paradox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Парадокс')),
                ('is_choices', models.BooleanField(default=True, verbose_name='Участвует в выборе')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Парадокс активен')),
            ],
            options={
                'verbose_name': 'Парадокс',
                'verbose_name_plural': 'Парадоксы',
            },
        ),
        migrations.RunPython(load_fixtures),
    ]
