import enum

TYPE_BUTTON = "button"
TYPE_CHECKBOX = "checkbox"
TYPE_COLOR = "color"
TYPE_DATE = "date"
TYPE_DATETIME_LOCAL = "datetime-local"
TYPE_EMAIL = "email"
TYPE_FILE = "file"
TYPE_HIDDEN = "hidden"
TYPE_IMAGE = "image"
TYPE_MONTH = "month"
TYPE_NUMBER = "number"
TYPE_PASSWORD = "password"
TYPE_RADIO = "radio"
TYPE_RANGE = "range"
TYPE_RESET = "reset"
TYPE_SEARCH = "search"
TYPE_SELECT = "select"
TYPE_SUBMIT = "submit"
TYPE_TEL = "tel"
TYPE_TEXT = "text"
TYPE_TEXTAREA = "textarea"
TYPE_TIME = "time"
TYPE_URL = "url"

# class BootstrapStyle(enum.StrEnum):
#     DEFAULT = "default"
#     PRIMARY = "primary"
#     SECONDARY = "secondary"
#     SUCCESS = "success"
#     DANGER = "danger"
#     WARNING = "warning"
#     INFO = "info"
#     LIGHT = "light"
#     DARK = "dark"
#     LINK = "link"
