# Generated by Django 4.1.7 on 2023-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'permissions': [('see_menu_admin', 'Может видеть меню администратора'), ('open_menu_admin', 'Может открыть меню администратора')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
